services:
    api:
        build: .
        ports:
            - "3333:3333"
        volumes:
            - .:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
            - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/devdb
        depends_on:
            - postgres

    postgres:
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: devdb
        volumes:
            - pgdata:/var/lib/postgresql/data

    apache:
        image: httpd:2.4
        container_name: mx-apache-yml
        ports:
            - "8080:80"
        volumes:
            - ./static:/usr/local/apache2/htdocs

volumes:
    pgdata:
